### PR TITLE
Add muscle terms

### PR DESCRIPTION
**Pull request by gouttegd**
This PR add terms for somatic muscles, where “muscle” is to be understood as representing the entire anatomical structure made of both actual muscle cells _and_ the associated tendon cells.

Having proper terms for muscles, instead of terms for muscle cells only, is among other things needed for the fly anatomograms, for which a technical requirement is that cells must always be `part_of` a precise anatomical structure. This will also increase consistency with the Uberon and CL cross-species ontologies (even though for now Uberon itself is not entirely consistent in its way of representing muscles, see obophenotype/uberon#2350 for how this will be fixed).

In details, this PR:

* adds `somatic muscle`, as the root of the entire hierarchy of somatic muscle terms;
* for each descendant of `somatic muscle cell`, create a corresponding muscle term and make the cell term a `part_of` the newly added muscle term.

The definitions for the new muscle terms are taken from the old definitions of the cell terms, before those were updated last year when we renamed all muscle cell terms to better indicate that they were about _cells_ and not the muscle themselves.

When muscle cell terms have `part_of`, `attached_to`, `attached_to_part_of`, `capable_of_part_of` relationships, those relationships are moved over to the corresponding muscle terms. `has_characteristic`, `overlaps`, and `receives_synaptic_input_from_neuron` relationships are copied over to the corresponding muscle terms, but also left to the cell terms. Other relationships (`expresses`, `develops_from`) are left to the cell terms only.

related to #1128

### CODE REVIEW

**Comment by Clare72** [comment]
There still seem to be 'attached to' relationships in EquivalentTo axioms on some of the cell terms

Screenshot 2022-07-06 at 13 10 54

**Comment by Clare72** [comment]
(above would also apply to grouping terms like 'adult pharynx muscle cell')

**Comment by gouttegd** [comment]
Yes, when I mentioned the `attached_to` relationships, I only meant the relationships that are not part of logical definitions (so `SubClassOf`, not `EquivalentTo`). I have left all logical definitions untouched.

I agree with the idea of logically defining _all_ muscle cell terms in terms of `'muscle cell' part_of some <corresponding muscle>`.

**Comment by gouttegd** [comment]
If we do define all somatic muscle cells as `'muscle cell' and (part_of some '<muscle X>')`, I think we should also re-define `somatic muscle cell` as `'muscle cell' and (part_of some 'somatic muscle')`, so that all somatic muscle cells are automatically classified as such.

The alternative would be to define individual muscle cells as `'somatic muscle cell' and (part_of some '<muscle X>')`, but automatic classification seems more logical to me.

**Comment by Clare72** [comment]
Yes, all should follow the same pattern (would be nice to properly patternise this with DOSDP at some point).

**Comment by Clare72** [comment]
FBbt:00058859 and FBbt:00058955 have labels beginning with 'a ', which isn't good. Can also be removed from respective cell type terms.
Also 'midgut muscle' and 'foregut muscle' are missing 'cell' from the label.

I am wondering if it would be better to just auto-generate the cell definitions (i.e. replace with ".", so they will become "any muscle cell that is part of some <muscle>.") and keep the more detailed definitions on the muscle terms. Some of them currently read a bit awkwardly (especially where there is more than one sentence).

I also see a lot of cases where we have unnecessary grouping classes (only one child exists) and that problem will now be doubled, but I think maybe that is not a problem to be solved today.

Otherwise this is looking pretty good now, the hierarchy of muscle cells looks nice.

**Comment by gouttegd** [comment]
> Also 'midgut muscle' and 'foregut muscle' are missing 'cell' from the label.

Those were missed during last year’s mass renaming of `muscle` to `muscle cell` – I’ll fix them now.

**Comment by gouttegd** [comment]
> I am wondering if it would be better to just auto-generate the cell definitions (i.e. replace with ".", so they will become "any muscle cell that is part of some .") and keep the more detailed definitions on the muscle terms. Some of them currently read a bit awkwardly (especially where there is more than one sentence).

I agree. The original definitions were written as if they were about the _muscles_, not the cells. Turning them into definitions about cells (by adding “Muscle cell of…” or similar at the beginning) was bound to give sometimes imperfect results.

All the original definitions are now carried by the muscle terms, so we wouldn’t lose any information by removing the definitions on the cell terms. If you agree with that I’ll do it in this PR.

**Comment by gouttegd** [comment]
> I also see a lot of cases where we have unnecessary grouping classes (only one child exists) and that problem will now be doubled, but I think maybe that is not a problem to be solved today.

Another problem that was left untouched for now is about the synonyms. Some of the synonyms that are carried by the cell terms should either be amended or transferred to the corresponding muscle term.

For example, if we take `lunula muscle cell` (which is now part of some `lunula muscle`), it has an EXACT synonym `lunular muscle` – this is no longer exact. We should either rename the synonym to `lunular muscle cell`, or move it to the `lunula muscle` term (or even do both).

I was planning to leave that for a future PR.

**Comment by Clare72** [comment]
Looks good to me now (except for synonym and redundant term issues to fix later).

**Review by Clare72 — APPROVED** [review]

**Pull request merged**
