### PR TITLE
Descending neurons - robot-generated terms

### PR DESCRIPTION
**Pull request by Clare72**
I would like to have this checked as it is rather a lot of terms, with quite a bit of detail.
I made a template and generated the terms for the descending neurons, based on the supplementary spreadsheets.
I will probably manually edit the DNx01 neuron - this one is a bit strange as its soma is not in the brain (it is in the antenna), but wanted to make sure the autogeneration was ok before starting to do these things.

### CODE REVIEW

**Comment by dosumis** [comment]
Looks great.  One small thing - I think it's worth adding the short names (e.g. DNa01) as synonyms.  

As these are the names used by Janelia (FlyLight) too, I think we should make tag them as official symbols.  This will require adding a synonymtypedef to the OBO file. 

e.g. synonymtypedef: official_symbol

=> an new synonymtypedef AP in OWL.

It may not be easy to get to support this type tagging with ROBOT.  If so - tagging should be split out to a separate edit.

**Comment by Clare72** [comment]
Ok, I will look into that.
What I initially thought you were taking about with synonyms was the list of similar neurons provided in a supplementary table. I have added these as comments, e.g. for DNg34:
>comment: Namiki et al., 2018 (FBrf0239335), identify this as being morphologically similar to the octopaminergic VPM1 neuron (FBbt:00110149), described by Busch et al., 2009 (FBrf0207458) and the fruitless aDT8 neuron (FBbt:00110543), described by Yu et al., 2010 (FBrf0211884).

Does this seem like a sensible approach rather than synonyms or using the existing term?
I thought they could be merged in future if they turned out to refer to the same thing.

**Comment by dosumis** [comment]
> What I initially thought you were taking about with synonyms was the list of similar neurons provided in a supplementary table. I have added these as comments, e.g. for DNg34:

> comment: Namiki et al., 2018 (FBrf0239335), identify this as being morphologically similar to the octopaminergic VPM1 neuron (FBbt:00110149), described by Busch et al., 2009 (FBrf0207458) and the fruitless aDT8 neuron (FBbt:00110543), described by Yu et al., 2010 (FBrf0211884).

> Does this seem like a sensible approach rather than synonyms or using the existing term?
> I thought they could be merged in future if they turned out to refer to the same thing.

I think this is fine for now, but we should probably find a way to formalise this soon as I suspect we'll be seeing more and more of this and will want to be able to create links and track provenance. We need to define an annotation property that can be used to directly refer to potential type mappings.  The axiom could then be annotated further with a comment and a reference indicating why this.  I've had a little chat to Nico and he's not aware of any such property. 

I've requested this from IAO:

https://github.com/information-artifact-ontology/IAO/issues/207

**Comment by Clare72** [comment]
Short names are now added as VFB synonyms.
If the new 'may be identical to' annotation will be ready within the next week or so, it is probably best to wait for it rather than retrofit, if not I guess it is best to get the terms in in time for the next release.

**Comment by dosumis** [comment]
> If the new 'may be identical to' annotation will be ready within the next week or so, it is probably best to wait for it rather than retrofit, if not I guess it is best to get the terms in in time for the next release.

AP is now in IAO (see linked ticket).  Please just add manually for now & use.  We can work on a standard IAO import later. Can you try to annotate the axioms with an rdfs:comment & an xref?  I think this should be possible using ROBOT.  Please ask for help if you have problems.

**Comment by Clare72** [comment]
Where a term was already in the ontology, I have put the FBbt number in the new IAO:0006011 field, annotated with the FBrf - does this seem like sensible usage? Some of the similar neurons weren't in the ontology (e.g. flycircuit neurons), so I thought it would make sense to leave all the comments as they were (i.e. not attached to IAO:0006011). Do you think this looks ok?

**Pull request merged**
