### PR TITLE
DH44 neuron additions

### PR DESCRIPTION
**Pull request by Clare72**

### CODE REVIEW

**Comment by dosumis** [comment]
DH44 neuron can be formally defined with expresses relationship to flybase gene.  Look for uses if expresses object property in fbbt for examples.

**Comment by Clare72** [comment]
I tried just adding the FlyBase IRI as it appeared for other entries, but I guess that was too simple... Do I need to fill in something manually or is there a way to import?

**Comment by dosumis** [comment]
* Build fail is my fault.  Looks like I accidentally pushed changes to travis config file to this branch instead of an experimental one I was working on.  I'll revert.

* FlyBase IRI is fine.  I still need to work on an import job for this (needs a script that queries FlyBase).  

* General class should have equivalentClass def + need to split classes to make all-some assertions true:

```diff
name: DH44 neuron
def: "DH44-expressing neuron. Three bilateral pairs of these cells exist in the pars intercerebralis, all of which co-express leucokinin receptor. There are also DH44 neurons in the ventral nerve cord." [FlyBase:FBrf0152168, FlyBase:FBrf0232426]
- is_a: FBbt:00005130 ! neurosecretory neuron
- relationship: expresses http://flybase.org/reports/FBgn0012344
+ intersection_of: FBbt:00005130 ! neurosecretory neuron
+ intersection_of: expresses http://flybase.org/reports/FBgn0012344
- relationship: has_soma_location FBbt:00005802 ! pars intercerebralis
```

If you leave the soma location in as a relationship, this is a very strong statement:  All neurosecretory neurons that express DH44 have soma in the PI.  Judging by the textual definitions of the subclasses, this is not the case.  


> name: adult DH44 neuron
> def: "DH44-expressing neuron of the adult. Three pairs of these are present in the pars intercerebralis and clusters are also present in the thoracico-abdominal ganglion (ventral nerve cord). DH44 neurons have been associated with desiccation tolerance and sugar sensing in the adult." [FlyBase:FBrf0152168, FlyBase:FBrf0228903, FlyBase:FBrf0232426]
> intersection_of: FBbt:00047126 ! DH44 neuron
> intersection_of: part_of FBbt:00003004 ! adult
> relationship: has_postsynaptic_terminals_in FBbt:00110639 ! adult subesophageal zone
> relationship: has_presynaptic_terminals_in FBbt:00007513 ! adult gut
> relationship: has_soma_location FBbt:00003700 ! adult pars intercerebralis
> relationship: has_soma_location FBbt:00004052 ! thoracico-abdominal ganglion

It's not possible for all of these neurons to have a soma the TAG *and* the PI (at least I don't know of any neurons with two cell bodies).  So this needs to be split into two classes, one for the PI, one for the TAG with the assertions about synaptic terminals going to the appropriate subclass (assuming they apply to all neurons in that subclass).


> name: larval DH44 neuron
> def: "DH44-expressing neuron of the larva. Three pairs of DH44-positive cell bodies are found in the pars intercerebralis. The larval ventral nerve cord contains more DH44 neurons than that of the adult." [FlyBase:FBrf0152168, FlyBase:FBrf0232426]
> ntersection_of: FBbt:00047126 ! DH44 neuron
> intersection_of: part_of FBbt:00001727 ! larva
> relationship: has_soma_location FBbt:00111670 ! larval pars intercerebralis
> relationship: overlaps FBbt:00001726 ! embryonic/larval corpus cardiacum

See comments on adult DH44 neuron.  Looks like a similar split is required here.

**Comment by dosumis** [comment]
Looks good.  Couple of minor issues.

* Annotation property error here: {comment="FlyBase:FBrf0228903"}
* part_of relationships should be to the finest level of granularity possible.  In this case adult and larval CNS terms would likely be granular enough.

**Comment by dosumis** [comment]
I think I've fixed the build issue.  Should be apparent next time you commit to this branch.   We now have a conflict though.   Let me know if you need help fixing.

**Comment by dosumis** [comment]
For the conflict resolution - try 

git checkout master
git pull
git checkout DH44
git merge

Then open in Aquamacs and search for ===

**Comment by Clare72** [comment]
Thanks, this is probably what I was on my way to doing - was looking for a cleverer way to find the conflicts in aquamacs than just searching, but I suppose that works

**Comment by Clare72** [comment]
Not really sure why, but the subclasses are inferred neurosecretory and peptidergic neurons, but the parent class ('DH44 neuron') is not. Also some of the adult/larva specific ones are not part of the adult or larva, is this a difference between 'part of' and 'has soma location'?

**Comment by Clare72** [comment]
I guess I need to keep a 'part of' term for this to work properly

**Comment by dosumis** [comment]
We could add an axiom to bridge has_soma_location to terms for animal at whole stage for gross stages

has_soma_location some adult subClassOf part_of some adult

etc.

These should go in FBbt_ext

**Comment by Clare72** [comment]
Ok, thanks. Do you know why 'DH44 neuron' is not coming up as neurosecretory or peptidergic, but subclasses are?

**Comment by Clare72** [comment]
Ok, just pushed the latest version. I will keep working on the neuropils for the time being.

**Comment by dosumis** [comment]
New version looks good to me locally.  Haven't yet traced the reason for the build fail.  Not connected to edits to terms - some odd problem with imports.

**Comment by dosumis** [comment]
Can you pull and take a look at classification of terms under 'dorsomedial neurosecretory cell' following classification.  Do my edits make sense?  Do inferred classifications now make sense to you?

**Comment by Clare72** [comment]
With dorsomedial neurosecretory cell defined as any neurosecretory neuron of the PI, all PI DH44 neurons are now a subclass. Looking at the descriptions for adult and larval dorsomedial neurosecretory cells, I'm not sure that this was the intended definition - there only 7 cells per hemisphere - does that sound right for the number of neurosecretory cells in the PI?

'DH44 neuron' is now inferred to be neurosecretory and peptidergic, which is good.

**Comment by dosumis** [comment]
> With dorsomedial neurosecretory cell defined as any neurosecretory neuron of the PI, all PI DH44 neurons are now a subclass. Looking at the descriptions for adult and larval dorsomedial neurosecretory cells, I'm not sure that this was the intended definition - there only 7 cells per hemisphere - does that sound right for the number of neurosecretory cells in the PI?

Yeh - I wasn't 100% confident about this.  I think it fits with the historical usage of the term (which, IIRC,  is very old and used for multiple insects), but the text description added by Marta may use a tighter interpretation.   Perhaps safer to make a general class 'pars intercerebralis neurosecretory cell' and have dorsomedial neurosecretory cell as a subclass.  Can you skim through the main references on adult and larval dorsomedial neurosecretory cell to check which strategy is reasonable given the terminology they use?

**Comment by Clare72** [comment]
I think these classes need some editing. All the references are about IPCs and the adult and larval versions both have 'insulin producing cell' as an exact synonym, maybe the name of the class should make this clearer? They also have 'median neurosecretory cell' as an exact synonym. Median neurosecretory cells expressing 3 different dilps are found in the PI, but there are other dilps, so I guess there are other IPCs...

**Comment by dosumis** [comment]
> I think these classes need some editing. All the references are about IPCs and the adult and larval versions both have 'insulin producing cell' as an exact synonym, maybe the name of the class should make this clearer? They also have 'median neurosecretory cell' as an exact synonym. Median neurosecretory cells expressing 3 different dilps are found in the PI, but there are other dilps, so I guess there are other IPCs...

OK.  Seems reasonable to re-assess.  Quite snowed under with work, so happy to leave to your judgement of the biology unless you have something specific you want me to read on this.

**Comment by Clare72** [comment]
I changed 'dorsomedial neurosecretory cell' classes to 'brain insulin-producing cell' classes (there are also insulin-producing cells in the VNC and gut).

There is now no generic class for a neurosecretory neuron of the PI - not sure whether that is a problem. Also no 'dorsomedial neurosecretory cell' class. Many papers refer to medial/median neurosecretory cells - this seems to be a superclass for the brain IPCs, but I couldn't find a definition anywhere...

Do these seem like things that ought to be in the ontology? If so I will create a new ticket for them. I think we should close this one unless something looks wrong with what I have done so far.

**Comment by dosumis** [comment]
For the renames I'd prefer 

brain insulin-producing cell
->
insulin secreting cell of brain

etc.

Worth making the general classes for 'neurosecretory cell of pars intercerbralis' synonym: 'median neurosecretory cell' & removing this synonym from the newly renamed insulin-producing cell.

Happy to merge once these are done.

**Pull request merged**
