### PR TITLE
Fix embryonic sensory organ precursors

### LINKED ISSUE #1224: Under-defined terms for larval sensory organ precursors
We have a bunch of terms under `sensory mother cell` that are completely lacking any definition and references:

* `lateral abdominal {bd1,ch,da,es}`
* `lateral thoracic {da,es}`
* `ventral abdominal {bd1,ch,da,es,td}`
* `ventral thoracic {ch1,da,es}`

The grouping terms for the clusters to which those cells belong, under `peripheral nervous system precursor cluster`, are lacking definition and references as well.

### PR DESCRIPTION
**Pull request by gouttegd**
This PR updates several terms under _sensory mother cell_ and _peripheral nervous system cluster_ to:

* obsolete several unused terms;
* improve classification;
* add definitions where needed;
* make it apparent in the terms’ labels that we are talking about precursors.

Closes #1224

### CODE REVIEW

**Review by Clare72 — COMMENTED** [review]
Looks mostly good, few comments:
It would be nice to have it made more explicit where terms refer to embryonic cells/clusters (I think anything that is or is part of a specific embryonic cluster). I think precursor cell types that are not linked to a cluster or a larval cell type can be non-specific (can include precursors of adult cells).
It would also be nice to add the develops_from relationships to terms for mature clusters/neurons/sense organs, but perhaps that should be on another ticket.
Regarding the 'ventral' terms, "v" stands for ventral, making it difficult to later differentiate "v" from the broader meaning of ventral. In the larva, I renamed the encompassing term to "larval ventral sensory cluster group", with "larval ventral sensory cluster" and "larval ventral' sensory cluster" having part_of relationships. I think something similar needs to happen with the embryonic terms, but maybe this can be tackled when the develops_from relationships are added as it is part of the alignment between precursors and mature structures.

**Comment by gouttegd** [comment]
> It would be nice to have it made more explicit where terms refer to embryonic cells/clusters (I think anything that is or is part of a specific embryonic cluster).

Would you recommend making “embryonic” part of the label? I considered it, but decided against it because several of those terms already have pretty long labels and I wasn’t too keen on adding another “embryonic“ adjective to them.

We could add it least to the terms for the “precursor clusters” (e.g., “embryonic dorsal abdominal sensory organ precursor cluster“). Then it would become part of the (auto-generated) definitions for all the terms representing the precursors in those clusters.


> I think precursor cell types that are not linked to a cluster or a larval cell type can be non-specific (can include precursors of adult cells).

I agree. Terms such as _chordotonal organ precursor cell_ or _bidendritic sensory organ precursor cell_, etc., can remain stage-neutral.


> In the larva, I renamed the encompassing term to "larval ventral sensory cluster group", with "larval ventral sensory cluster" and "larval ventral' sensory cluster" having part_of relationships. I think something similar needs to happen with the embryonic terms.

It would make sense to mimic the structure used for the later clusters indeed. This could also include adding terms to represent the lateral/dorsal/ventral clusters above the magma level, e.g. going from

* dorsal abdominal sensory organ precursor cluster
* dorsal thoracic sensory organ precursor cluster
* lateral abdominal sensory organ precursor cluster
* etc.

to

* dorsal sensory organ precursor cluster
  * dorsal sensory organ precursor cluster of A1-7
  * thoracic sensory organ precursor cluster
* lateral sensory organ precursor cluster
  * lateral sensory organ precursor cluster of A1-7
  * thoracic lateral sensory organ precursor cluster

**Comment by Clare72** [comment]
>several of those terms already have pretty long labels

Haha, you should see some of the central complex neurons! We generally tend to err on the side of long, clear labels to avoid misuse. In this case, being precursors, perhaps these terms are not so ambiguous. And having it in the definition would be fine.

>It would make sense to mimic the structure used for the later clusters indeed

Yeah, though I think that this alignment (including adding develops_from relationships) should be another ticket (this diff is already quite long).

**Comment by gouttegd** [comment]
> Haha, you should see some of the central complex neurons!

Fair point. :)

> And having it in the definition would be fine.

OK, so for this PR I will just add `embryonic` to the terms for the precursor clusters, so that the definitions for all the precursors that are part of said clusters will mention that.

> I think that this alignment (including adding develops_from relationships) should be another ticket (this diff is already quite long).

Agreed.

**Review by Clare72 — APPROVED** [review]

**Pull request merged**
