### PR TITLE
Update metadata annotation

### PR DESCRIPTION
**Pull request by gouttegd**
This PR replaces all `oboInOwl:created_by` and `oboInOwl:creation_date` annotations by `dcterms:contributor` and `dc:date` annotations, respectively.

In addition, wherever possible, “old-style” contributor identifiers (consisting typically of a CRS ID or similar initials) are replaced by proper ORCID IRIs.

There are a few old-style identifiers that couldn’t be mapped to ORCID IRIs: `dos`, `david`, and `sr544`. For those, the annotations have been changed to `dcelements:contributor` instead (for which there is no requirement that the value is a valid IRI), and the values have been prefixed with `FBC:`.

There is little doubt, I think, that `dos` and `david` both represent David Osumi-Sutherland, but given that at least two other “Davids” have worked for FlyBase over the years, I didn’t change those identifiers for David’s ORCID IRI without confirmation. We can always update them later.

As for `sr544` (Simon Reeve), I didn’t follow Nico’s suggestion to create a Wikidata entry: I am reluctant to create an entry for a person I know nothing about apart from the fact that he has worked for FlyBase at some point. Again, we can update the corresponding annotation later if needed.

### CODE REVIEW

**Comment by Clare72** [comment]
>The job exceeded the maximum log length, and has been terminated.

hmm, wonder if there is a way to hide all the 'Unrecognized tag' output

**Comment by gouttegd** [comment]
I think it should be fixed in `OboModel.pm`: https://github.com/FlyBase/flybase-controlled-vocabulary/blob/9fddeb926956dfdf07bf9a72ea1e9e363cf800e4/external_tools/perl_modules/releases/OboModel.pm#L75

`property_value` should be added there in the list of recognised tags.

**Comment by Clare72** [comment]
If you are happy doing this then you can try it (I don't know perl)

**Comment by Clare72** [comment]
wow, output looks so much better!

**Comment by Clare72** [comment]
I think this is ok for now, but we should try to sort out outstanding editors soon, so maybe leave #1459 open for now (or make a new ticket).

**Review by Clare72 — APPROVED** [review]

**Pull request merged**
