### PR TITLE
Larvalbrain mapping

### PR DESCRIPTION
**Pull request by Clare72**
Efforts to add linkouts to larvalbrain site.

Have not merged links in as there is not a good way to remove them if they need editing.

Additions to fbbt-edit have been added on another branch.

### CODE REVIEW

**Comment by dosumis** [comment]
Hi Clare 

- is this still blocked on how to run this using imports?  If so can't we just specify an --output larvalbrain_xrefs.owl in the robot template command and then add an import statement for this to fbbt-edit.owl.

Or am I missing something?

Cheers,  David

**Comment by Clare72** [comment]
Probably. I wasn't sure how this worked. The other imports have 'purl.obolibrary...' IRIs, but look at a local file (beginning with Users/clare...). Do I need to set up a 'purl.obolibrary...' IRI for each import? If I tell it to look in my /imports folder for the file, will it still work for other people?

**Comment by dosumis** [comment]
> Probably. I wasn't sure how this worked. The other imports have 'purl.obolibrary...' IRIs, but look at a local file (beginning with Users/clare...). Do I need to set up a 'purl.obolibrary...' IRI for each import? If I tell it to look in my /imports folder for the file, will it still work for other people?

You can use the robot annotate command:  to set the IRI of the output file:

robot template --input-iri http://purl.obolibrary.org/obo/ro.owl --template template.tsv --output larvalbrain_xrefs.owl annotate --ontology-iri http://purl.obolibrary.org/obo/fbbt/imports/larvalbrain_xrefs.owl

Put the resulting file in your imports directory.  Manually add an import statement to fbbt-edit.owl to pull this in.  You should then check that your [catalog xml file](https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/master/fbbt/src/ontology/catalog-v001.xml) has the entry:

<uri id="Imports Wizard Entry" name="http://purl.obolibrary.org/obo/fbbt/imports/larvalbrain_xrefs.owl" uri="imports/larvalbrain_xrefs.owl"/>

We should also find somewhere to publicly post the mapping tables so that they can potentially be used by larvalbrain.org to link to us.

Finally - it might be easier to update in future if you bundle the robot commands into a Makefile.  I can help with this.

**Comment by Clare72** [comment]
Related to https://github.com/VirtualFlyBrain/Management/issues/160
import of linkouts for compartments and fascicles on larvalbrain site
some file rearrangement

**Comment by Clare72** [comment]
>We should also find somewhere to publicly post the mapping tables so that they can potentially be used by larvalbrain.org to link to us.

>Finally - it might be easier to update in future if you bundle the robot commands into a Makefile. I can help with this.

These things are not done yet

**Pull request merged**
